name: Pérola Negra Store API - CI (Maven)

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: maven

            - name: Tests
              run: mvn test -B

            - name: Build
              run: mvn clean install -B -DskipTests
